---
username: "{{ lookup('env', 'USER') }}"

create_directories: true
directories:
  - $HOME/Documents/repositories/

configure_sudoers: true
sudoers_custom_config: |
  # Allow users in sudo group to use sudo with no password.
  %sudo ALL=(ALL) NOPASSWD: ALL

configure_dotfiles: true
dotfiles_repo: https://github.com/AlexNabokikh/dotfiles
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Documents/repositories/dotfiles
dotfiles_files:
  - .gitconfig
  - .p10k.zsh
  - .tmux.conf
  - .vimrc
  - .zshrc

install_fonts: true
installed_nerdfonts:
  - Meslo

apt_packages:
  - fzf

install_snap: true
snap_packages:
  - name: nvim
    classic: true

install_flatpak: true
flatpak_packages:
  - name: Steam

install_homebrew: true
homebrew_packages:
  - name: tfenv

pip_packages:
  - name: pip
    state: latest

npm_packages:
  - name: neovim
    state: latest

configure_zsh: true
# Plugin names have to be in the format github_user/plugin_name
zsh_plugins:
  - zsh-users/zsh-syntax-highlighting
  - zsh-users/zsh-history-substring-search

# Theme names have to be in the format github_user/theme_name
zsh_themes:
  - romkatv/powerlevel10k

configure_tmux: true
tmux_dir: $HOME/.tmux
