---
- name: WSL Playbook
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]

  tasks:
    - import_tasks: tasks/apt.yml
      tags: ["apt"]

    - name: Include directories task configuration.
      ansible.builtin.import_tasks:
        file: tasks/directories.yml
      when: create_directories
      tags: ["directories"]

    - name: Include extra-packages task configuration.
      ansible.builtin.import_tasks:
        file: tasks/extra-packages.yml
      when: install_extra_packages
      tags: ["extra-packages"]

    - name: Include gpg task configuration.
      ansible.builtin.import_tasks:
        file: tasks/gpg.yml
      when: configure_gpg
      tags: ["gpg"]

    - name: Include homebrew task configuration.
      ansible.builtin.import_tasks:
        file: tasks/homebrew.yml
      when: homebrew_installed
      tags: ["homebrew"]

    - name: Include sudoers task configuration.
      ansible.builtin.import_tasks:
        file: tasks/sudoers.yml
      when: configure_sudoers
      tags: ["sudoers"]

    - name: Include vim-plug task configuration.
      ansible.builtin.import_tasks:
        file: tasks/vim-plug.yml
      when: install_vim_plug
      tags: ["vim"]

    - name: Include zsh task configuration.
      ansible.builtin.import_tasks:
        file: tasks/zsh.yml
      when: configure_zsh
      tags: ["zsh"]

    - name: Include tmux task configuration.
      ansible.builtin.import_tasks:
        file: tasks/tmux.yml
      when: configure_tmux
      tags: ["tmux"]
