---
- name: Ubuntu Playbook!
  hosts: all

  vars_files:
    - example.config.yml

  pre_tasks:
    - name: Include main playbook configuration.
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  roles:
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]

  tasks:
    - name: Include apt packages task configuration.
      ansible.builtin.import_tasks:
        file: tasks/apt.yml
      tags: ["apt"]

    - name: Include directories task configuration.
      ansible.builtin.import_tasks:
        file: tasks/directories.yml
      tags: ["dirs"]

    - name: Include extra-packages task configuration.
      ansible.builtin.import_tasks:
        file: tasks/extra-packages.yml
      tags: ["extra-packages"]

    - name: Include fonts task configuration.
      ansible.builtin.import_tasks:
        file: tasks/fonts.yml
      when: install_fonts
      tags: ["fonts"]

    - name: Include homebrew task configuration.
      ansible.builtin.import_tasks:
        file: tasks/homebrew.yml
      tags: ["homebrew"]
      when: install_homebrew

    - name: Include hostname configuration.
      ansible.builtin.import_tasks:
        file: tasks/hostname.yml
      tags: ["hostname"]

    - name: Include snap packages task configuration.
      ansible.builtin.import_tasks:
        file: tasks/snap.yml
      tags: ["snap"]
      when: install_snap

    - name: Include sudoers task configuration.
      ansible.builtin.import_tasks:
        file: tasks/sudoers.yml
      when: configure_sudoers
      tags: ["sudoers"]

    - name: Include zsh task configuration.
      ansible.builtin.import_tasks:
        file: tasks/zsh.yml
      when: configure_zsh
      tags: ["zsh"]
