---
- name: Install apt packages.
  become: true
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    autoclean: true
    autoremove: true
    update_cache: true
    state: latest
  loop: "{{ apt_packages }}"
  register: install_result
  when: apt_packages is defined

- name: Clean apt cache.
  become: true
  ansible.builtin.command: >
    apt clean && apt autoremove && apt autoclean
  when: apt_packages is defined and not install_result.skipped
