---
- name: Install apt packages.
  become: true
  ansible.builtin.package:
    name: "{{ item.name | default(item) }}"
    state: latest
  loop: "{{ native_packages }}"
  register: install_result
  when: native_packages is defined
