---
- name: Install apt packages.
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    autoclean: true
    autoremove: true
    update_cache: true
    state: latest
  loop: "{{ apt_packages }}"
  when: apt_packages is defined
  become: true
  register: install_result

- name: Clean apt cache.
  ansible.builtin.command: >
    apt clean && apt autoremove && apt autoclean
  when: apt_packages is defined and not install_result.skipped
  become: true
