---
- name: Install global NPM packages.
  community.general.npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: true
    executable: "{{ item.executable | default(omit) }}"
  loop: "{{ npm_packages }}"
  loop_control:
    label: "{{ item.name }}"
  when: npm_packages is defined

- name: Install global Pip packages.
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default('pip3') }}"
    extra_args: "{{ item.extra_args | default(omit) }}"

  loop: "{{ pip_packages }}"
  loop_control:
    label: "{{ item.name }}"
  when: pip_packages is defined
