---
- name: Ensure flatpak installed.
  become: true
  ansible.builtin.apt:
    name: flatpak
    state: latest

- name: Ensure flatpak remotes are installed.
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak packages.
  become: "{{ 'true' if item.method is defined and item.method == 'system' else 'false' }}"
  community.general.flatpak:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    method: "{{ item.method | default('user') }}"
    remote: "{{ item.remote | default('flathub') }}"
  with_items: "{{ flatpak_packages }}"
  when: flatpak_packages is defined
