---
- name: Register path to sed.
  ansible.builtin.command: which sed
  register: sed_which_result
  changed_when: false
  when: sed_path is undefined

- name: Define sed_path variable.
  ansible.builtin.set_fact:
    sed_path: "{{ sed_which_result.stdout }}"
  when: sed_path is undefined

- name: Copy sudoers configuration into place.
  ansible.builtin.copy:
    content: "{{ sudoers_custom_config }}"
    dest: /etc/sudoers.d/custom
    mode: 0440
    validate: "visudo -cf %s"
  become: true
